version: '3'

services: 
  postgres:
    image: postgres:12-alpine
    environment:
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=yngdieng
    ports:
    - "127.0.0.1:5432:5432"
    volumes:
    - ./pg_data:/var/lib/postgresql/data
    - /tmp/pg_share:/pg_share/
    restart: always
